roma_bigquery:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: "{{ env_var('PROJECT_ID') }}"
      dataset: "{{ env_var('BQ_DATASET_ID') }}"
      threads: 1
      keyfile: "{{ env_var('GCP_SERVICE_ACCOUNT_PATH') }}"
